name: RSS Import

on:
  # schedule:
  #   # Run every hour at minute 0
  #   - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  import:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog_mt_importer
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run database migrations
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: blog_mt_importer
        run: npm run typeorm migration:run

      - name: Import RSS feeds
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: blog_mt_importer
          # Add your Gemini API key as a GitHub secret
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: npm run cli -- rss:import --all

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: rss-import-logs
          path: logs/
          retention-days: 7

      # Optional: Send notification on failure
      - name: Send failure notification
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'RSS import failed!'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        continue-on-error: true